### ISSUE TITLE
R 安装问题

### ISSUE THREAD

**Issue by XuliangSUFE** [JiaxiangBU/tutoring#11]
安装过程的问题
![image](https://user-images.githubusercontent.com/49772882/56403586-93734e00-6294-11e9-9af7-618f0e811e60.png)
![image](https://user-images.githubusercontent.com/49772882/56403598-a2f29700-6294-11e9-82ec-52625f6a91d7.png)
这一个是安装问题，
![image](https://user-images.githubusercontent.com/49772882/56403836-d97ce180-6295-11e9-9b1e-bdc01dfbfcba.png)
![image](https://user-images.githubusercontent.com/49772882/56403850-e8639400-6295-11e9-94ad-99bdda30ffc6.png)
这边chunk看不太懂 而且那个安装也出问题了

**Comment by JiaxiangBU** [comment]
> 安装过程的问题
> ![image](https://user-images.githubusercontent.com/49772882/56403586-93734e00-6294-11e9-9af7-618f0e811e60.png)

你看这个报错，先按照链接里面这个软件即可。

**Comment by JiaxiangBU** [comment]
> 这边chunk看不太懂 而且那个安装也出问题了

这个你搜索 RMarkdown 的介绍看下就明白了，这是一个数据化文档的设计，类似地，Jupyter Notebook 都回用到。

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57496659-c4302b80-7306-11e9-99e9-c29ede2a1d22.png)学长请问这边的read_utf8()是什么意思呢？utf8格式？

**Comment by JiaxiangBU** [comment]
以 `UTF-8` 的格式录入文件。

```r
?read_utf8
```

可以查看 help 文档。

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 学长 gdata和XLconnect这两个包忽略就可以呀？

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57515069-5dc9fe00-7344-11e9-94a7-275b052b9c06.png)
学长这一个包下载用install下载会显示没有安装工具
![image](https://user-images.githubusercontent.com/49772882/57516716-ce264e80-7347-11e9-9096-d468e4cfe15a.png)

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 然后试着直接下载安装包安装就显示package'的长度必需为一

**Comment by JiaxiangBU** [comment]
@XuliangSUFE 你方便把你的报错复制上来吗？格式是

````

```r
# 你的代码
```

````

**Comment by XuliangSUFE** [comment]
![image](https://user-images.githubusercontent.com/49772882/57522108-6cb8ac80-7354-11e9-8165-9307581d3241.png)

**Comment by JiaxiangBU** [comment]
@XuliangSUFE 还是需要你粘贴的代码而非截图。

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 

8. | stop("Could not find tools necessary to compile a package", call. = FALSE)
-- | --

**Comment by XuliangSUFE** [comment]
![image](https://user-images.githubusercontent.com/49772882/57522958-311ee200-7356-11e9-8bd4-3c9296bf1c44.png)
这个之前就安装了的

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57527865-4f3f0f00-7363-11e9-9040-40a695c33cc5.png)
![image](https://user-images.githubusercontent.com/49772882/57527890-5bc36780-7363-11e9-96f3-04cddbea9ba0.png)
学长，我不太理解这边list下面的data_mtcars = mtcars,
     data_iris   = iris   第一个mtcars文件夹是能找到的 第二个无法找到；但是自己但测试其他的文件时不知道该怎么写上文件名，
![image](https://user-images.githubusercontent.com/49772882/57528231-66323100-7364-11e9-8ca7-de16870de10f.png)就是这样，第一张表格就成了C:/Users/Huang/Desktop/aa

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57531286-a6e17880-736b-11e9-93ef-5c7d9ca7952a.png)学长这边here的包已经安装了，但是依旧是找不到路径的问题？？

**Comment by JiaxiangBU** [comment]
因此如果不是 R 和 RStudio 安装的问题，可以新开一个 Issue 进行讨论。
