### ISSUE TITLE
json2dataframe

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#21]

**Comment by slsongge** [comment]
@JiaxiangBU
家翔哥，还是json2dataframe的问题哈。我用你的代码如下图：
![image](https://user-images.githubusercontent.com/36298417/56857945-a2998080-69a5-11e9-8af2-22426ebc9ec4.png)
返回的结果如下图：
![image](https://user-images.githubusercontent.com/36298417/56857949-bb099b00-69a5-11e9-9e07-2a5fd25b671e.png)
后面再用unnest()函数的时候，就会报错，如下图：
![image](https://user-images.githubusercontent.com/36298417/56857961-d7a5d300-69a5-11e9-8656-d3d7b3875b81.png)
他的意思是数据类型转换的问题，但是我发现并不是这个原因，而是json_col列variables不同导致的。这个可咋办是好呢？

**Comment by slsongge** [comment]
@JiaxiangBU  不好意思哈，不太会用，不小心关闭了。我重新写一遍：
json2dataframe的问题，我用你给我的代码（下图）：
![image](https://user-images.githubusercontent.com/36298417/56858688-f3fb3d00-69b0-11e9-810a-bb4efa4f6f63.png)
返回的结果是这样的（下图）：
![image](https://user-images.githubusercontent.com/36298417/56858695-142afc00-69b1-11e9-9a54-65d4cea7581a.png)
我在使用unnest函数的时候就会报错（下图）：
![image](https://user-images.githubusercontent.com/36298417/56858702-30c73400-69b1-11e9-9832-34db9dd66889.png)
虽然报错内容是某个变量的类型问题，但是我感觉并不是这个原因，我认为是最后一列json_col的variables不同导致的，我取前三行进行unnest的时候就不报错了，即验证了我的猜想。但是问题来了，json的key确实不同，这个咋办？

**Comment by JiaxiangBU** [comment]
@slsongge 底下有一个 `reopen issue` 打开即可。

**Comment by JiaxiangBU** [comment]
报错的变量`*_score`没看到，它的结构是什么样子的？

**Comment by slsongge** [comment]
> 报错的变量`*_score`没看到，它的结构是什么样子的？

该字段的结构如下：是字符型的
![image](https://user-images.githubusercontent.com/36298417/56859510-b00f3480-69be-11e9-96d3-8dc2ca68c2eb.png)
 
> 需要看下你这个 json 的格式，是元素还是序列。

json的格式就是{"key_1": value_1, "key_2": value_2, ..., "key_n": value_n}

**Comment by JiaxiangBU** [comment]
乱改一个，发一个例子上来 @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU 
我在github里面不会提交数据，所以给你发邮件了哈。

**Comment by JiaxiangBU** [comment]
@slsongge 看 [文档](jinxiaosong/json2dataframe/json2df-2019-04-28.md)
