### ISSUE TITLE
@JiaxiangBU 学长 gdata和XLconnect这两个包忽略就可以呀？

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring#34]
@JiaxiangBU 学长 gdata和XLconnect这两个包忽略就可以呀？

_Originally posted by @XuliangSUFE in https://github.com/JiaxiangBU/tutoring/issues/11#issuecomment-491185489_

**Comment by JiaxiangBU** [comment]
@XuliangSUFE

这两个包，我个人觉得不好用，所以你可以忽略。
另外的话是有一部分需要实时交互Excel的用户比较喜欢这两个包，因此为了全面，我就都放进来了。
我建议利用 rio 和 readxl 就差不多了，后面一个是 RStudio 支持的，bug 少很多。

**Comment by XuliangSUFE** [comment]
好哒
