### ISSUE TITLE
here 包的问题

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring#36]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57531286-a6e17880-736b-11e9-93ef-5c7d9ca7952a.png)学长这边here的包已经安装了，但是依旧是找不到路径的问题？？

_Originally posted by @XuliangSUFE in https://github.com/JiaxiangBU/tutoring/issues/11#issuecomment-491291484_

**Comment by JiaxiangBU** [comment]
@XuliangSUFE 这是一个特定包的问题，因此新开一个 Issue。

`here`函数会指定一个 R Project 的当前路径。这个当前路径你可以

```
here::here()
```

查看。

另外通过

```r
?here::here()
```

阅读 help 文档。

**Comment by XuliangSUFE** [comment]
@JiaxiangBU 
![image](https://user-images.githubusercontent.com/49772882/57576960-0e4c1500-749f-11e9-939e-de72a1c633ec.png)
![image](https://user-images.githubusercontent.com/49772882/57576963-2d4aa700-749f-11e9-8369-56b89744d715.png)不理解这边的load.R 我找到了这个文件的路径加到here函数中还是有问题，不知道这边一定是得用这个问题嘛学长？

**Comment by JiaxiangBU** [comment]
@XuliangSUFE 

这个文件是没有提供给你，从目前你学的进度来看，你暂时可以忽略这个函数，**之后我再教你调用外部函数**。
