### ISSUE TITLE
xgb中缺失值的处理方式

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#43]
@JiaxiangBU 
家翔哥，抽空分享一下xgb对于缺失值的处理方式吧。辛苦！

**Comment by JiaxiangBU** [comment]
你可以参考这个GitHub Pages https://jiaxiangbu.github.io/learn_xgboost/translatein2sql/README_sql
里面我保留了源代码可以下载。

**Comment by slsongge** [comment]
> 你可以参考这个GitHub Pages https://jiaxiangbu.github.io/learn_xgboost/translatein2sql/README_sql
> 里面我保留了源代码可以下载。

收到，辛苦！
