### ISSUE TITLE
相关性和决策树的关系

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring#48]
100755 jinxiaosong/corr_c50_test.html

![image](https://user-images.githubusercontent.com/15884785/58034791-ebce9180-7b59-11e9-88b7-e2404e2d624c.png)

**Comment by JiaxiangBU** [comment]
先查看下文件

**Comment by JiaxiangBU** [comment]
@slsongge 晓松，我看了你的文件结论，

> 针对完全相关的变量会选择input顺序靠前的变量

结果是没有问题的，那么我觉得这种100%相关的变量都能处理成这样，难保相关性  <100% 相关的情况，还有更复杂的多重共线性。

我觉得这样用模型前，需要先看下多重共线性是否严重了，一般有一个检验去检验，你有兴趣可以去查一下。

**Comment by slsongge** [comment]
@JiaxiangBU 
> 我觉得这样用模型前，需要先看下多重共线性是否严重了，一般有一个检验去检验，你有兴趣可以去查一下。

好的，我以为多重共线性就是单纯的高线性相关性呢，回头我在深入了解一下多重共线性。
