### ISSUE TITLE
在线性回归中如何变换x，从而使x与y高度线性相关

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#49]
@JiaxiangBU 
家翔哥，我现在在做一个多项式线性回归的模型，希望连续性变量x与y之间有强线性相关的关系，但是不知道如何变换x。
辛苦！

**Comment by JiaxiangBU** [comment]
你可以参考 `jinxiaosong/poly-regression.md`

其中有两个，你可以扩展去看

https://github.com/JiaxiangBU/tutoring/commit/9919001e5556322be32f3cb43a83e8229836fd9d#diff-47764f352a2decd5fd552845adfb240dR124
https://github.com/JiaxiangBU/tutoring/commit/9919001e5556322be32f3cb43a83e8229836fd9d#diff-47764f352a2decd5fd552845adfb240dR130

**Comment by slsongge** [comment]
@JiaxiangBU 
这个没有看的太懂，大概意思是 只要变量足够多，哪怕是同一个变量的衍生，都能拟合的很好，但是就过拟合了对吗？

**Comment by slsongge** [comment]
@JiaxiangBU 
还有一个就是多元一次线性回归的例子，比如y = 2x1 + 3x2 +1，这个东西是三维空间的一个平面吗？

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU
> 这个没有看的太懂，大概意思是 只要变量足够多，哪怕是同一个变量的衍生，都能拟合的很好，但是就过拟合了对吗？

你注意看泰勒公式。

$$f(x)=\frac{f(a)}{0 !}+\frac{f^{\prime}(a)}{1 !}(x-a)+\frac{f^{\prime \prime}(a)}{2 !}(x-a)^{2}+\ldots+\frac{f^{(n)}(a)}{n !}(x-a)^{n}+R_{n}(x)$$

任何y 都可以被一个可导的x表示，但是这样也过拟合了。

本身预测y这个问题是努力去预测y的泛化部分，而非它的 $\mu$，也就是误差，因此做这种次方的特征变量，过拟合风险太容易发生，因此一般地，大家使用交叉项，而非次方项目。

**Comment by slsongge** [comment]
> 本身预测y这个问题是努力去预测y的泛化部分，而非它的 $\mu$，也就是误差，因此做这种次方的特征变量，过拟合风险太容易发生，因此一般地，大家使用交叉项，而非次方项目。

@JiaxiangBU 
交叉项有什么套路吗？还是说就是随机的两两交互呢？

**Comment by JiaxiangBU** [comment]
目前讨论的是交叉项，放到另外一个问题了。
