### ISSUE TITLE
@JiaxiangBU

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/tutoring#50]
@JiaxiangBU 
还有一个就是多元一次线性回归的例子，比如y = 2x1 + 3x2 +1，这个东西是三维空间的一个平面吗？

_Originally posted by @slsongge in https://github.com/JiaxiangBU/tutoring/issues/49#issuecomment-494693464_

**Comment by JiaxiangBU** [comment]
这个地方 三维空间是哪三维？

**Comment by slsongge** [comment]
> 这个地方 三维空间是哪三维？

x1,x2,y就是三维吧？

**Comment by JiaxiangBU** [comment]
是的 @slsongge
