### ISSUE TITLE
多个模型融合疑问

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#54]
@JiaxiangBU 
家翔哥，有一个问题一直困扰着我，如下：
有很多中方式的模型融合对吧，比如在分类模型中，可以讲各个模型的分类结果取众数作为最后结果；可以讲各模型返回的概率和因变量用逻辑回归建模，返回的概率作为最后的结果；还有就是在建模的过程中融合，等等……
但是我听说模型融合的时候要要求各模型返回结果的独立性更高，那么怎么就能证明独立性高呢？
我有一个想法，比如我同样的数据带入贝叶斯和决策树，因为这两个模型的原理不同，是不是能说明这两个模型返回的结果独立性更高呢？或者说把原始数据拆分为两个（其中变量不同，样本量相同），分别用贝叶斯和决策树建模，是不是这样才算是真正的独立，或者比上一个办法的独立性更高呢？
辛苦家翔哥！

**Comment by JiaxiangBU** [comment]
> 有很多中方式的模型融合对吧，比如在分类模型中，可以讲各个模型的分类结果取众数作为最后结果；可以讲各模型返回的概率和因变量用逻辑回归建模，返回的概率作为最后的结果；还有就是在建模的过程中融合，等等……

这个地方没有特别看得懂，但是“取众数”只是其中一种。

**Comment by JiaxiangBU** [comment]
> 但是我听说模型融合的时候要要求各模型返回结果的独立性更高，那么怎么就能证明独立性高呢？
> 我有一个想法，比如我同样的数据带入贝叶斯和决策树，因为这两个模型的原理不同，是不是能说明这两个模型返回的结果独立性更高呢？或者说把原始数据拆分为两个（其中变量不同，样本量相同），分别用贝叶斯和决策树建模，是不是这样才算是真正的独立，或者比上一个办法的独立性更高呢？

模型原理、样本分离都是可以处理的方式，更直接的是在 stacking 的时候使用，证明各个预测值相关性低。
这个可以查看华泰证券这篇研究报告，在之前凤凰金融我们用到过。

**Comment by slsongge** [comment]
收到！
