### ISSUE TITLE
wkNN 算法 逻辑

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#55]
@JiaxiangBU 
家翔哥，你了解这个算法的原理吗？https://rdrr.io/cran/kknn/man/train.kknn.html
我尝试找中文的原理讲解，发现找不到。

**Comment by JiaxiangBU** [comment]
> Hechenbichler K. and Schliep K.P. (2004) Weighted k-Nearest-Neighbor Techniques and Ordinal Classification, Discussion Paper 399, SFB 386, Ludwig-Maximilians University Munich (http://www.stat.uni-muenchen.de/sfb386/papers/dsp/paper399.ps)

http://www.stat.uni-muenchen.de/sfb386/papers/dsp/paper399.ps
这个我没有打开，你看看你可以打开吗？我打算看看。

**Comment by slsongge** [comment]
链接确实打不开，我能找到上面的那个论文，就是复制粘贴到Google就行了

**Comment by JiaxiangBU** [comment]
哦，发下我？直接拖过来？

**Comment by slsongge** [comment]
我给你微信了，你是没登录吗？

**Comment by slsongge** [comment]
@JiaxiangBU 
这个是那篇论文的链接：https://epub.ub.uni-muenchen.de/1769/1/paper_399.pdf

**Comment by JiaxiangBU** [comment]
@slsongge 好的我先看一下。

**Comment by JiaxiangBU** [comment]
@slsongge 

我看了 wkNN 这篇文章，目前我对这个算法的想法是

- 集成了 kNN 的优点
- 更加受到距离计算、标准化的影响，可能是“成也萧何败也萧何”

因此当这个算法表现不好的时候，有可能是 kNN 本身算法不适合数据集，也可能是距离计算、标准化处理有问题，wkNN 受到影响更大，还不如 kNN。

具体见  https://jiaxiangbu.github.io/learn_knn/analysis/knn-learning-notes.html#wknn

**Comment by slsongge** [comment]
> 我看了 wkNN 这篇文章，目前我对这个算法的想法是
> 
> * 集成了 kNN 的优点
> * 更加受到距离计算、标准化的影响，可能是“成也萧何败也萧何”
> 
> 因此当这个算法表现不好的时候，有可能是 kNN 本身算法不适合数据集，也可能是距离计算、标准化处理有问题，wkNN 受到影响更大，还不如 kNN。

理解。

**Comment by slsongge** [comment]
> 具体见 https://jiaxiangbu.github.io/learn_knn/analysis/knn-learning-notes.html#wknn

文章写的越来越标准了，看起来更舒服了，赞，后期我也学习一下！

**Comment by JiaxiangBU** [comment]
好啊，我觉得基本上用这个算法需要注意的地方，已经总结完了。
我先 close 了。
