### ISSUE TITLE
多元回归中哑变量的疑问

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#57]
@JiaxiangBU 
家翔哥，现在又有一个小问题：我在做多元回归的时候（房价~面积+城区+等等），然后发现因为城区的取值很多，从而导致R^2显著增高了。如下图所示：
![image](https://user-images.githubusercontent.com/36298417/58380694-d25c9800-7fe6-11e9-8495-3256c0573c76.png)
那么我认为这样做是不太合理的，感觉可以把这些城区做一个处理（目的为了不让自变量个数太多）。但是我不知道怎么处理更合理，希望你讲一下。
辛苦！！！

**Comment by JiaxiangBU** [comment]
分类变量的处理，一种是 onehot，也就是你的做法，一种是 integer encoding，将其转换成自然数，但是我看到你是回归模型，第二种是不适用的。


目前来看，就是计算woe，合并一些分类项，这是评分卡常用的。

**Comment by slsongge** [comment]
@JiaxiangBU 
收到，谢谢家翔哥，我想一下，你忙你的。

**Comment by JiaxiangBU** [comment]
@slsongge 还有一个 embedding 的，回头我发一个例子给你。

**Comment by slsongge** [comment]
@JiaxiangBU   好呀，你咋啥都知道。

**Comment by JiaxiangBU** [comment]
@slsongge

https://jiaxiangbu.github.io/learn_nn/analysis/introduction-to-tensorflow-in-python/tensorflow-20-learning-notes.html#embedding

embedding 的内容在这。
