### ISSUE TITLE
Gitbook 使用

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#59]
@JiaxiangBU 
家翔哥，我看你用Bookdown生成的结果比Markdown返回的html好看，所以想简单学一下，不用特别详细哈。
所以想要你一个小的案例的源码，比如那个5.31号你写的wkNN的那个结构就行，我感觉这样比我从头学效率更高。
这个不着急哈，你抽空就行。
辛苦！

**Comment by JiaxiangBU** [comment]
- [ ] 生成 template
- [ ] build a add2gitbook

**Comment by slsongge** [comment]
> * [ ]  build a add2gitbook

@JiaxiangBU 
你这是又要自己写包吗？看着是add2开头的

**Comment by JiaxiangBU** [comment]
@slsongge 弄好了，用这个包 https://github.com/JiaxiangBU/add2gitbook
