### ISSUE TITLE
分组统计各列缺失值的个数和占比

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#6]
df <- tibble(A = as.character(c(1,1,1,0,0)), B = c(NA,NA,10,NA,20), D = c(NA,10,10,20,20)); df

rs <- tibble(col_names = c('B','D'), na_num_1 = c(2,1), 
             na_num_0 = c(1,0), na_per_1 = c(2/3, 1/2), 
             na_per_0 = c(1/3,0)); rs

从df处理成rs，当然目的只是统计缺失值个数和占比，不一定和rs一模一样，达到目的就行。不过就是数据一定是两行五列的哈。这个不急，我今晚估计也能做出来。
辛苦，家翔哥！

**Comment by JiaxiangBU** [comment]
完成了，见https://github.com/JiaxiangBU/tutoring/blob/master/jinxiaosong/na-summary.md
