### ISSUE TITLE
回归中，y经过boxcox转换之后，自变量系数的解释？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#60]
@JiaxiangBU 
我在做二手房单价预测时，拟合了一个方程，然后我想解释自变量的系数，但是不知道如何解释？解释的结构大概是下图这样：
![image](https://user-images.githubusercontent.com/36298417/59100163-d201bc80-8957-11e9-8230-84c356b04394.png)

**Comment by JiaxiangBU** [comment]
嗯，晓松给下我复现的代码（就是方程上的）和数据（预测的），我在基础上给你举例。 @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU 
代码在这里：https://github.com/JiaxiangBU/rfm-discussion/blob/master/analysis/code_jxg.Rmd
数据在这里：https://github.com/JiaxiangBU/rfm-discussion/blob/master/refs/df_end.xlsx

**Comment by JiaxiangBU** [comment]
- [ ] 比如 tpo 跟我说 y 不做变换的，只对 x，这个找下相关例子。

**Comment by slsongge** [comment]
> 比如 tpo 跟我说 y 不做变换的，只对 x，这个找下相关例子。
@JiaxiangBU  没看懂你得这句话是啥意思。

**Comment by JiaxiangBU** [comment]
> > 比如 tpo 跟我说 y 不做变换的，只对 x，这个找下相关例子。
> > @JiaxiangBU  没看懂你得这句话是啥意思。

哦，这是我自己记录的，准备跟你说。

**Comment by JiaxiangBU** [comment]
> * [ ]  比如 tpo 跟我说 y 不做变换的，只对 x，这个找下相关例子。

https://github.com/tidymodels/recipes/issues/231#issuecomment-433383578

@slsongge 一般地，会考虑在 x 上做变换，这个我之前问过类似的问题给 caret 包的作者，他基本上设计的包 boxcox 函数也是针对 x 变量，而非 y 变量。

**Comment by slsongge** [comment]
@JiaxiangBU 
这个意味着我当前的回归方程不能去解释吗？

**Comment by JiaxiangBU** [comment]
目前我看到有两个方程，所以不知道是哪一个，我先针对 `lm_1`

https://github.com/JiaxiangBU/rfm-discussion/blob/9b272788bf63729c3a25f3cf2d2c226098dc387f/analysis/code_jxg.Rmd#L168-L183

这里 y 变量对所有 x 进行回归，没看出来有什么变换。

```
> summary(df_raw$PriceUnitBC)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1788  2.1804  2.7237  2.7009  3.2125  5.3857 
```
但是这样应该有你说的变换。

**Comment by slsongge** [comment]
PriceUnitBC  后面的BC指的是我经过了boxcox变换了  没在那个代码中，不好意思，我忘了。变换代码如下：
![image](https://user-images.githubusercontent.com/36298417/59144884-cde4a600-8a0e-11e9-95df-d0bbc5f2e591.png)

**Comment by JiaxiangBU** [comment]
先简单的说，如果 `PriceUnitBC` 就是正常收集的数据，没有进行变换。

那么查看回归结果

```
> summary(lm_1)

Call:
lm(formula = PriceUnitBC ~ ., data = .)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.11150 -0.26248 -0.01354  0.25477  2.47915 

Coefficients:
                Estimate Std. Error t value Pr(>|t|)    
(Intercept)    1.7982521  0.0379581  47.375  < 2e-16 ***
Area          -0.0023590  0.0002105 -11.206  < 2e-16 ***
...
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.439 on 14959 degrees of freedom
Multiple R-squared:  0.6824,	Adjusted R-squared:  0.6816 
F-statistic:   846 on 38 and 14959 DF,  p-value: < 2.2e-16
```

```
> summary(df_raw$Area)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21.11   57.69   83.25   87.90  109.45  297.48 
```

当其他变量不变的情况下，`Area` 增加一个单位， 这个变换过的`PriceUnitBC ` 增加 ` -0.0023590`个单位，并且有`< 2e-16`的概率这个结论为0。

**Comment by JiaxiangBU** [comment]
由于 `PriceUnitBC` 的变换是非线性的，那么斜率 `-0.0023590` 不是对每个 `Area` 的点都很多恒定了，因此是非线性关系。

**Comment by JiaxiangBU** [comment]
@slsongge 因此这是我的说，把问题弄复杂了。

**Comment by slsongge** [comment]
> 由于 `PriceUnitBC` 的变换是非线性的，那么斜率 `-0.0023590` 不是对每个 `Area` 的点都很多恒定了，因此是非线性关系。

后面应该有错别字吧，`都很多恒定了`，没理解你的意思。

> 因此这是我的说，把问题弄复杂了。

这个也没有太明白，哪里复杂了呢？

**Comment by JiaxiangBU** [comment]
> > 由于 `PriceUnitBC` 的变换是非线性的，那么斜率 `-0.0023590` 不是对每个 `Area` 的点都很多恒定了，因此是非线性关系。
> 
> 后面应该有错别字吧，`都很多恒定了`，没理解你的意思。
> 
> > 因此这是我的说，把问题弄复杂了。
> 
> 这个也没有太明白，哪里复杂了呢？

我想了下不好举例子，你看看这个，
https://jiaxiangbu.github.io/tutoring/jinxiaosong/interpret-beta.html

**Comment by slsongge** [comment]
> 我想了下不好举例子，你看看这个

@JiaxiangBU  居然还有你不会举的例子。 好的  再看

**Comment by slsongge** [comment]
> https://jiaxiangbu.github.io/tutoring/jinxiaosong/interpret-beta.html

@JiaxiangBU  链接打不开，你哪里能打开吗？

**Comment by JiaxiangBU** [comment]
打得开吧，微信里面我试了下。
@slsongge

**Comment by slsongge** [comment]
现在行了 ，刚才我这里不行，显示404

**Comment by JiaxiangBU** [comment]
嗯，目前这个问题应该没问题了？ @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU 没问题了，后续我自己研究一下吧，当前感觉不适合研究，哈哈
