### ISSUE TITLE
回归中，某些离散型变量特征值不平衡如何处理？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#61]
@JiaxiangBU  家翔哥，我由来找你了啊，哈哈。
### 问题一

- [ ] 在二手房单价回归中，自变量出现如下图（自变量中出现某些特征值占比很小）情况一般该怎么处理呢？

![image](https://user-images.githubusercontent.com/36298417/59155214-f1632b80-8ab6-11e9-8c9d-28a8e47f42dc.png)

### 问题二

- [ ] 在二手房单价回归中，自变量出现如下图（自变量中出现暂无数据or未知）情况一般该怎么处理呢？

![image](https://user-images.githubusercontent.com/36298417/59155226-2b343200-8ab7-11e9-9462-b576a6f82729.png)

**Comment by JiaxiangBU** [comment]
> * [ ]  在二手房单价回归中，自变量出现如下图（自变量中出现某些特征值占比很小）情况一般该怎么处理呢？

如果是树模型，一般情况是我不处理，因为分类少并不影响什么。
对于逻辑回归来说，也不影响，因为分类变量你都进行了 one-hot 因此无论是否是稀少情况，有自己对应的评分就好了。

不太会出现老金说的这个问题

> 不要剔除。不然以后遇到这个类型的不能预测了。至少随机森林我遇到过。

因为你树模型预测时的底层逻辑是 `case when`，当预测集出现一个训练集内没有时，只要加上这样一个条件即可。

```sql
case 
    when ... then ...
    when ... then ...
    ...
    when x1 is null then ...
    when x1 is true then ... -- (等于 x1 is null 的情况)
    end as x1
```

**Comment by JiaxiangBU** [comment]
> * [ ]  在二手房单价回归中，自变量出现如下图（自变量中出现暂无数据or未知）情况一般该怎么处理呢？

你查看数据上是否和 `NA` 情况是相同，如果是，就两者合并。
因为没有其他业务信息，所以下一步我也不太清楚。

**Comment by slsongge** [comment]
> 在二手房单价回归中，自变量出现如下图（自变量中出现暂无数据or未知）情况一般该怎么处理呢？
>> 你查看数据上是否和 `NA` 情况是相同，如果是，就两者合并。因为没有其他业务信息，所以下一步我也不太清楚。

之所以突然间问这个问题，是因为我认为这个分类变量（比如房屋类型[复式、平层等]）应该是必须有一个对应的类别的，那么被标记为“暂无数据”的样本说不定是哪个类型的，这样如果将这个变量oneot的话，明显是不对的，因为暂无数据不能作为一个单独的类别。哪怕即使模型的结果很好，我感觉不能接受和解释。

**Comment by JiaxiangBU** [comment]
> 那么被标记为“暂无数据”的样本说不定是哪个类型的，这样如果将这个变量oneot的话

没有其他信息的情况下，只能这么处理。

**Comment by slsongge** [comment]
> > 那么被标记为“暂无数据”的样本说不定是哪个类型的，这样如果将这个变量oneot的话
> 
> 没有其他信息的情况下，只能这么处理。

如果是当作NA去插补呢？比如说用随机森林之类的进行插补，把还有缺失的列中缺失值作为未标记的因变量进行插补？

**Comment by JiaxiangBU** [comment]
> 如果是当作NA去插补呢？比如说用随机森林之类的进行插补，把还有缺失的列中缺失值作为未标记的因变量进行插补？

可以这么处理，但是你假设的情况是，缺失值是随机缺失的，满足你的非缺失样本的分布。但是如果不是随机缺失的呢？

因此这种处理方式是更实际的看，这种处理后，最后对预测效果是否有帮助。

**Comment by slsongge** [comment]
> 可以这么处理，但是你假设的情况是，缺失值是随机缺失的，满足你的非缺失样本的分布。但是如果不是随机缺失的呢？

理解你的意思，我认为当前的数据背景而言，“暂无数据”这个大概率是随机的吧。就像你当时kaggle那个房价预测时填补和游泳池相关的一个字段的时候，我这个情况应该和你当时那个更类似吧。

主要是针对当前的数据背景，我个人认为可以把暂无数据当作一组去处理，主要原因就是无法解释这一类。你应该能理解我的想法吧？

**Comment by JiaxiangBU** [comment]
> > 可以这么处理，但是你假设的情况是，缺失值是随机缺失的，满足你的非缺失样本的分布。但是如果不是随机缺失的呢？
> 
> 理解你的意思，我认为当前的数据背景而言，“暂无数据”这个大概率是随机的吧。就像你当时kaggle那个房价预测时填补和游泳池相关的一个字段的时候，我这个情况应该和你当时那个更类似吧。
> 
> 主要是针对当前的数据背景，我个人认为可以把暂无数据当作一组去处理，主要原因就是无法解释这一类。你应该能理解我的想法吧？

那么按照随机这个思路继续走，假设有两个缺失的变量，那么你准备如何填补缺失值，必然有一个先后顺序，那么得到的填补效果是不一样的，有2种，如果是三个，那么就是6种，这就复杂了。

这个过程你打算怎么设计？

@slsongge

**Comment by JiaxiangBU** [comment]
@slsongge 晓松，目前这个问题解决了吗？
