### ISSUE TITLE
如何将list数据转化成df

### ISSUE THREAD

**Issue by jmbb93** [JiaxiangBU/tutoring#62]
问题：

```python
db_list=[]
for i in range(len(db)):
    db_list.append(pd.DataFrame(db[i],index=[0]))
```

报错信息：

```python
ValueError: could not broadcast input array from shape (162) into shape (1)
```

希望结果：怎么修正上面的代码？

原始数据地址在https://github.com/wesm/pydata-book/tree/2nd-edition/datasets/usda_food

**Comment by JiaxiangBU** [comment]
@jmbb93 Python 执行代码？

**Comment by JiaxiangBU** [comment]
@jmbb93 参考 commit https://github.com/JiaxiangBU/tutoring/commit/3ad0f9a472fb7a31078d1de6a9c47efd3e802dc3
展示文档见https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/extract_subelement_in_json.md
ipynb 见 https://github.com/JiaxiangBU/tutoring/blob/3ad0f9a472fb7a31078d1de6a9c47efd3e802dc3/wangjuan/analysis/.ipynb_checkpoints/extract_subelement_in_json-checkpoint.ipynb

**Comment by jmbb93** [comment]
import pandas as pd
import numpy as np

db = json.load(open('D:/jmbb/python/datasets/usda_food.json'))
db.head()

**Comment by JiaxiangBU** [comment]
> db = json.load(open('D:/jmbb/python/datasets/usda_food.json'))

这个函数用错了，和我的不一样。 @jmbb93

**Comment by jmbb93** [comment]
df_subset = pd.DataFrame(df.nutrients.iloc[1])
这里只取了索引=1的数据，所以只有237条数据，但实际上需要所有索引的数据，一共是37万条数据。

![image](https://user-images.githubusercontent.com/34465917/60315501-65e40880-9999-11e9-962b-2e57593e198b.png)

![image](https://user-images.githubusercontent.com/34465917/60315476-51077500-9999-11e9-9676-4d926a6277aa.png)

**Comment by JiaxiangBU** [comment]
> @jmbb93 参考 commit [3ad0f9a](https://github.com/JiaxiangBU/tutoring/commit/3ad0f9a472fb7a31078d1de6a9c47efd3e802dc3)
> 展示文档见https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/extract_subelement_in_json.md
> ipynb 见 https://github.com/JiaxiangBU/tutoring/blob/3ad0f9a472fb7a31078d1de6a9c47efd3e802dc3/wangjuan/analysis/.ipynb_checkpoints/extract_subelement_in_json-checkpoint.ipynb

@jmbb93 更新了结果了，你看看，但是 for 循环跑的好慢。

**Comment by JiaxiangBU** [comment]
> @jmbb93 参考 commit 3be583f
> 展示文档见https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/extract_subelement_in_json.md
> ipynb 见 https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/.ipynb_checkpoints/extract_subelement_in_json-checkpoint.ipynb

@jmbb93 加了 id，这个应该是非常简单的方法了。

**Comment by jmbb93** [comment]
解决了，赞👍

**Comment by JiaxiangBU** [comment]
好啊 ，我 close 了 @jmbb93

**Comment by JiaxiangBU** [comment]
@jmbb93 最近我复习了下 pandas 发现了更加简洁的方式，不需要写中间变量，见 commit https://github.com/JiaxiangBU/tutoring/commit/08c75790369ac3f733f10f4a5b1d1e0ac65b434a

```python
pd.concat([pd.DataFrame(df.iloc[i,].nutrients).assign(**{'id':df.iloc[i,].id}) for i in range(df.index.size)])
```

> > @jmbb93 参考 commit [6427af1](https://github.com/JiaxiangBU/tutoring/commit/6427af118f60d77a57963041b6e812f41f90b356)
> > 展示文档见https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/extract_subelement_in_json.md
> > ipynb 见 https://github.com/JiaxiangBU/tutoring/blob/master/wangjuan/analysis/.ipynb_checkpoints/extract_subelement_in_json-checkpoint.ipynb
> 
> @jmbb93 加了 id，这个应该是非常简单的方法了。
