### ISSUE TITLE
python中pptx模块如何做到实时返回ppt？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#65]
### 问题
使用python中的pptx模块创建PPT的过程中，能不能在jupyter中实时返回当前的PPT效果，好比我画了一个图（P_1），想看看这个图长啥样，使用plt.show()或着运行P_1即可输出该图。

### 希望输出的结果
我猜测下图的表格大概率是额外插入的，不像是直接输出的，但是我希望有直接输出的方法：

![image](https://user-images.githubusercontent.com/36298417/60768847-3b155500-a0fb-11e9-886b-bc889a83017f.png)

### 代码
```
# 如果没有安装pptx，使用pip install python-pptx即可

from pptx import Presentation
from pptx.util import Inches

prs = Presentation()
slide = prs.slides.add_slide(prs.slide_layouts[5])

x, y, cx, cy = Inches(2), Inches(2), Inches(4), Inches(1.5)
shape = slide.shapes.add_table(3,3,x,y,cx,cy)

shape

shape.has_table

table = shape.table

table
```

**Comment by slsongge** [comment]
@JiaxiangBU  补充一下，这个是链接：https://python-pptx.readthedocs.io/en/latest/user/table.html

**Comment by JiaxiangBU** [comment]
> 使用python中的pptx模块创建PPT的过程中，能不能在jupyter中实时返回当前的PPT效果，好比我画了一个图（P_1），想看看这个图长啥样，使用plt.show()或着运行P_1即可输出该图。

我觉得你这个思路，类似于这个 R 包的这个函数 `xaringan::moon_reader()`，但是这里插入的时候都是 HTML 如果用你说的截图的话，那么会很慢。 @slsongge

**Comment by JiaxiangBU** [comment]
> 我猜测下图的表格大概率是额外插入的，不像是直接输出的，但是我希望有直接输出的方法：
> 
> ![image](https://user-images.githubusercontent.com/36298417/60768847-3b155500-a0fb-11e9-886b-bc889a83017f.png)

根据这个表格，我觉得是比较特定的功能，我想的是你在做这个的时候，必须限定在 Python，相当于取数、清洗和展示都在 Python 里面进行，可以跨语言吗？比如 Python + R，因为 jupyter notebook 也可以支持 R。 @slsongge

**Comment by slsongge** [comment]
@JiaxiangBU   收到，我也是感觉不能直接输出这个表格，看表格的细节可以看出来是截图的（比如里面的光标和最外侧的边框）。虽然不如直接输出方便，但是可以随时保存通过office打开查看。

**Comment by JiaxiangBU** [comment]
@slsongge 你可以看看这个
5.5 模板代码
https://jiaxiangli.netlify.com/2018/01/30/rmarkdown/
