### ISSUE TITLE
R 提取指定字符后的字符串

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#70]
### 问题
用R语言提取某个字符串中指定字符后的字符串。
想要提取的字符串的特点：>想要提取的字符串"，即前后分别紧挨着>和“，例如 '"a_1_2>2000"'

### 参考代码
```
library(tidyverse) 
str_extract('"a_1_2>2000"', '>\\d+')
```

### 希望输出的结果
![image](https://user-images.githubusercontent.com/36298417/61509144-cbb73380-aa1f-11e9-9de3-7ae6f2d9a7f6.png)

**Comment by JiaxiangBU** [comment]
@slsongge 见 https://github.com/JiaxiangBU/tutoring/blob/master/jinxiaosong/string.md
