### ISSUE TITLE
直方图添加频数

### ISSUE THREAD

**Issue by Cobbybaby** [JiaxiangBU/tutoring#79]
简单描述你的问题和希望产生的输出结果。
事先可以在以下项目查看是否已经有解决方案

相关问题，assign 给对应 owner，打上对应的标签 label 等。

问题解决后，记得 close。

### 简述问题
有个年龄分布的直方图需要做，但是做完发现不能再直方图的柱子上加标签来表示相应bin上对应的数量
...

### 希望输出的结果

在直方图上添加每个组的数量标签

### 过程中产生的报错 (可选)

...

遇到报错的时候，推荐采用 debugging 思路，定位具体报错信息和报错的函数或者对象，具体可以参考例子
https://jiaxiangbu.github.io/learn_rstudioapi/analysis/rstudio-and-api-learning-notes.html#section-6.2

在书写 Rmd 文档时，

1. `library` 放在前面，先让第三方包 import，这样可以让后面的函数顺利执行。
1. 导入数据用相对路径，避免其他使用者需要重新修改路径。如果使用`here`函数，`?here::here` 查看使用方法
1. 不要重复定义函数，已经定义，使用 `source` 调用。
1. 文档编码是编码 `GBK`的，修改为 `UTF-8`，方法是在 RStudio 点击左上角的 <kbd>File</kbd>，点击 <kbd>Save with Encoding</kbd>，选择 `UTF-8`
1. 代码注意缩进，或者 <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>A</kbd>  reformat 代码
1. 很多 bug 都是书写不规范导致的，先 debug 一下看看。

### 有关联的问题

直接把链接复制在此。

### 复现代码和数据
R语言
library(ggplot2)
下面是年龄的那一列，家祥哥可以直接复制然后读图
age
18
46
54
56
29
41
46
53
42
56
27
24
28
58
47
22
56
32
39
48
33
59
39
57
41
56
45
42
53
27
23
21
19
50
23
18
21
28
57
58
30
44
25
24
42
30
42
24
19
18
34
30
20
25
23
38
46
21
56
53
21
24
55
30
32
26
34
40
26
53
38
32
48
42
28
29
28
46
53
58
30
45
44
41
29
46
32
47
47
29
56
25
30
34
29
34
21
36
39
29
27
27
40
33
28
29
22
34
52
42
40
41
46
26
56
41
21
24
23
42
56
36
41
30
55
43
34
37
51
32
28
36
47
47
39
47
45
36
27
53
54
28
52
38
32
18
31
55
44
41
26
28
33
59
39
32
50
54
36
48
42
47
42
53
26
36
55
51
29
44
40
28
40
56
38
22
45
40
58
56
34
36
30
53
45
48
30
26
34
38
46
53
36
52
38
30
34
45
41
32
18
53
32
46
35
32
35
36
39
44
40
38
37
41
36
46
32
56
36
33
30
28
34
26
40
30
53
43
25
22
32
37
32
51
33
35
22
36
51
27
59
39
45
30
50
53
31
31
48
46
32
53
48
53
31
49
32
30
49
48
32
25
19
41
39
30
22
29
29
44
41
22
42
58
56
54
42
49
58
28
46
51
47
22
24
36
26
28
35
26
35
42
43
17
27
25
32
45
40
28
19
43
41
41
44
43
47
53
28
34
41
36
32
30
34
27
30
52
36
32
30
30
24
34
17
37
25
19
21
21
34
19
20
20
20
30
36
28
27
21
39
27
40
31
48
34
48
22
47
32
17
37
27
31
31
34
18
35
22
23
21
23
25
24
46
38
20
43
24
19
21
26
30
49
31
21
32
19
40
34
22
42
21
32
28
22
24
26
17
28
33
18
32
28
24
49
29
46
36
21
46
37
38
38
36
24
38
39
24
41
28
37
48
37
36
44
27
45
32
38
31
31
37
45
44
18
36
39
40
40
33
32
25
29
35
41
26
46
33
30
43
45
36
28
29
50
46
40
37
43
35
34
38
39
43
26
27
26
32
31
28
26
57
26
26
34
41
33
27
28
26
42
41
31
34
32
35
24
35
39
18
36
36
30
23
23
16
46
46
21
32
36
37
41
40
18
18
45
19
29
30
30
30
42
35
24
17
28
36
36
26
43
30
26
44
44
17
36
33
40
43
29
48
33
31
21
39
35
44
34
34
39
24
22
26
47
42
39
28
48
49
32
45
32
26
39
35
50
33
37
17
21
37
40
50
22
19
58
30
31
41
37
30
38
23
32
20
26
26
38
38
34
44
39
37
45
29
32
26
36
45
31
42
46
38
31
42
38
32
37
44
33
29
36
31
50
37
19
38
45
56
32
29
27
37
27
23
41
39
49
45
45
43
53
36
45
41
30
37
44
47
30
24
46
44
35
48
26
45
33
40
43
26
29
39
52
25
45
56
34
30
30
49
48
26
39
34
34
32
38
27
25
38
38
25
31
45
43
24
25
22
43
22
32
26
30
42
32
30
25
25
24
43
36
49
41
43
42
26
18
19
48
43

age_hist <- read.table("clipboard",header = T)
p <- ggplot(data = age_hist,aes(x = age_hist))
p1 <- p + theme_minimal() + geom_histogram(stat="bin",binwidth = 1,bins = 5,breaks = seq(10,60,10),colour="black",fill = c(1:5)) + xlim(10,60) + ylim(0,250) +scale_y_continuous(breaks=seq(0, 250, 50)) + scale_x_continuous(breaks=seq(10, 60, 10)) 
###这个下面的就是标记直方图label的，但是标记不上
p2 <- p1 + geom_text(aes(label= as.character(..count..)),stat="bin",binwidth=1)

**Comment by JiaxiangBU** [comment]
@Cobbybaby 数据可以直接传到这个项目即可。

**Comment by JiaxiangBU** [comment]
@Cobbybaby 代码我改了下排版，见 https://github.com/JiaxiangBU/tutoring/blob/master/pansiyu/ggplot-annotate_bar.md

**Comment by Cobbybaby** [comment]
嗯嗯，我得好好熟悉一下github，以后得用这个，方便交流，谢谢家祥哥
 



------------------ 原始邮件 ------------------
发件人: "Jiaxiang Li"<notifications@github.com>; 
发送时间: 2019年8月18日(星期天) 晚上11:27
收件人: "JiaxiangBU/tutoring"<tutoring@noreply.github.com>; 
抄送: "指挥官"<276951867@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [JiaxiangBU/tutoring] 直方图添加频数 (#79)




@Cobbybaby 代码我改了下排版，见 https://github.com/JiaxiangBU/tutoring/blob/master/pansiyu/ggplot-annotate_bar.md

**Comment by JiaxiangBU** [comment]
@Cobbybaby 你查看这个答案，用汇总值即可。

> @Cobbybaby 代码我改了下排版，见 https://github.com/JiaxiangBU/tutoring/blob/master/pansiyu/ggplot-annotate_bar.md

**Comment by Cobbybaby** [comment]
嗯嗯，谢谢家祥哥啊
 



------------------ 原始邮件 ------------------
发件人: "Jiaxiang Li"<notifications@github.com>; 
发送时间: 2019年8月18日(星期天) 晚上11:32
收件人: "JiaxiangBU/tutoring"<tutoring@noreply.github.com>; 
抄送: "指挥官"<276951867@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [JiaxiangBU/tutoring] 直方图添加频数 (#79)




@Cobbybaby 你查看这个答案，用汇总值即可。
  
@Cobbybaby 代码我改了下排版，见 https://github.com/JiaxiangBU/tutoring/blob/master/pansiyu/ggplot-annotate_bar.md
