### ISSUE TITLE
回归中，若进行分层抽样，如何选取“分层变量”？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#82]
### 背景与问题
在分类问题中，直接对因变量作为分层变量进行分层抽样是一个正确的选择，但是在回归问题中，理论上应该找出一个与因变量关系最强的自变量进行分层，若关系最强的自变量是连续型，则分层时又需要分段。如上述描述的正确，那么我有以下两个疑问：

- [ ] 怎么才能找出与因变量关系最强的自变量？
- [ ] 找出该自变量之后，应该如何对其分段（等频、等距、聚类...）?

**Comment by JiaxiangBU** [comment]
> 在分类问题中，直接对因变量作为分层变量进行分层抽样是一个正确的选择，但是在回归问题中

从 sklearn 的角度，有三种k-fold 方式，

1. k-fold
1. 分层 k-fold
1. time-series k-fold

我记得我跟你举过一个例子。

> * Kaggle workflow 太偏工程，不用太在意其中的顺序，更多是因为工程上跑的顺畅 https://jiaxiangbu.github.io/learn_kaggle/learning_notes.html

```python
<script.py> output:
    Fold: 0
    CV train shape: (666, 9)
    Medium interest listings in CV train: 167
    
    Fold: 1
    CV train shape: (666, 9)
    Medium interest listings in CV train: 167
    
    Fold: 2
    CV train shape: (668, 9)
    Medium interest listings in CV train: 168
````

分层抽样的目的是保证 y 的分布在每个 fold 里面是一致的（简单的k-fold是做不到的，如果数据量小，是有误差的），那么回到你的这个问题。

对于一个回归问题，也应该是保证每个 fold 里面 y 的分布一致，对不对？ @slsongge

**Comment by JiaxiangBU** [comment]
@slsongge 晓松，你看看这么说你是否理解？没问题可以 close 了哈哈，我看看你的其他问题。

**Comment by slsongge** [comment]
@JiaxiangBU   在回归问题中，我考虑分层抽样的主要目的是为了让训练集和测试集中存在分层变量的每类特征值（当时并没有想到你上述的保持y的分布一致）。即比如我按照性别作为分层变量，那么如果样本不平衡（男：女=1000：1），可能导致训练集中都是男性，这样建模就有问题了。

**Comment by slsongge** [comment]
@JiaxiangBU  这个issue的问题有点偏离了，我的issue有问题，我先关了吧。
