### ISSUE TITLE
sns.pairplot中target为啥也被绘制到了图中？

### ISSUE THREAD

**Issue by slsongge** [JiaxiangBU/tutoring#85]
### 简述问题
在绘制pairplot的时候，字符型的target也被绘制到了图中，不知道为啥？

### 数据
我不知道怎么在issue中提交数据，所以就直接微信给你吧。

### 代码
```
import pandas as pd
import seaborn as sns

df = pd.read_csv("sns_pairplot_data.csv")
df.info()

sns.pairplot(df, hue='TARGET', plot_kws={'alpha':0.4})
```

**Comment by JiaxiangBU** [comment]
@slsongge 数据可以直接传到项目里面。

**Comment by JiaxiangBU** [comment]
![image](https://user-images.githubusercontent.com/15884785/63633995-66d8a400-c683-11e9-97a5-5227e53dd04d.png)

> 为什么target也会绘制进去
> 正常情况下，应该是类似这样的


![image](https://user-images.githubusercontent.com/15884785/63633997-68a26780-c683-11e9-8c88-b265d8d14ac6.png)

**Comment by slsongge** [comment]
@JiaxiangBU 
家翔哥，我知道是因为什么导致的了：虽然我的TARGET列是str类型的，但是里面的特征值为（‘0’， ‘1’）我猜测在画图的时候会自动转换为数值型；因为我刚才尝试将TARGET重塑为TARGET_STR（如果为0，则赋值为‘good’， 否则‘bad’），然后绘图就没有问题了。

所以说应该是一个bug！！！

![image](https://user-images.githubusercontent.com/36298417/63635098-fcc6fb80-c690-11e9-9843-989b42d38dd6.png)
